export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const DELETE_HISTORY_RECORD = 'DELETE_HISTORY_RECORD';

export const GET_CLICHES_SUCCESS = 'GET_CLICHES_SUCCESS';
export const ADD_CLICHE_SUCCESS = 'ADD_CLICHE_SUCCESS';
export const UPDATE_CLICHE_SUCCESS = 'UPDATE_CLICHE_SUCCESS';
export const DELETE_CLICHE_SUCCESS = 'DELETE_CLICHE_SUCCESS';
export const DELETE_CLICHE_HISTORY_RECORD = 'DELETE_CLICHE_HISTORY_RECORD';
